MACRO(LEMON CVAR HVAR)
    FOREACH(SRC ${ARGN})
      GET_FILENAME_COMPONENT(DST "${SRC}" PATH)
      GET_FILENAME_COMPONENT(NAME "${SRC}" NAME_WE)
      SET (C_ONAME ${CMAKE_CURRENT_BINARY_DIR}/${DST}/${NAME}.c)
      SET (H_ONAME ${CMAKE_CURRENT_BINARY_DIR}/${DST}/${NAME}.h)
      SET (LEMON_C_ONAME ${CMAKE_CURRENT_SOURCE_DIR}/${DST}/${NAME}.c)
      SET (LEMON_H_ONAME ${CMAKE_CURRENT_SOURCE_DIR}/${DST}/${NAME}.h)
      SET (LEMON_O_ONAME ${CMAKE_CURRENT_SOURCE_DIR}/${DST}/${NAME}.out)
      ADD_CUSTOM_COMMAND(
        OUTPUT ${C_ONAME} ${H_ONAME}
	BYPRODUCTS ${C_ONAME} ${H_ONAME}
        COMMAND cmake -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/${DST}"
	COMMAND $<TARGET_FILE:lexical::lemon> -s ${CMAKE_CURRENT_SOURCE_DIR}/${SRC} -T$<TARGET_FILE_DIR:lexical::lemon>/lempar.c
	COMMAND cmake -E copy ${LEMON_C_ONAME} ${C_ONAME}
	COMMAND cmake -E copy ${LEMON_H_ONAME} ${H_ONAME}
	COMMAND cmake -E remove ${LEMON_C_ONAME} 
	COMMAND cmake -E remove ${LEMON_H_ONAME}
	COMMAND cmake -E remove ${LEMON_O_ONAME}
        DEPENDS "${SRC}" 
        )
      SET(${CVAR} ${${CVAR}} ${C_ONAME})
      SET(${HVAR} ${${HVAR}} ${H_ONAME})
    ENDFOREACH()
ENDMACRO()


MACRO(RE2C VAR SRC)
  GET_FILENAME_COMPONENT(DST "${SRC}" PATH)
  GET_FILENAME_COMPONENT(NAME "${SRC}" NAME_WE)
  SET (ONAME ${CMAKE_CURRENT_BINARY_DIR}/${DST}/${NAME}.c)
  ADD_CUSTOM_COMMAND(
    OUTPUT "${ONAME}"
    BYPRODUCTS ${ONAME}
    COMMAND cmake -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/${DST}"
    COMMAND $<TARGET_FILE:lexical::re2c> -s -o ${ONAME} "${CMAKE_CURRENT_SOURCE_DIR}/${SRC}"
    DEPENDS "${SRC}"
    DEPENDS ${ARGN}
    )
  SET(${VAR} ${${VAR}} ${ONAME})
ENDMACRO()
